### ISSUE TITLE
generic name

### ISSUE THREAD

**Issue by ritz078** [tkh44/preact-shallow-compare#3]
This package works well with [inferno](https://github.com/trueadm/inferno) too as far as I have used. Maybe a generic name to the package that can be used at both places will be great.

**Comment by tkh44** [comment]
I agree.  Any ideas on a name?  'vdom-shallow-compare'?

**Comment by ritz078** [comment]
Even 'shallow-compare' is available. I have no issue with any name as far as its generic :)

**Comment by tkh44** [comment]
I didn't realize that. I'll look into how to change the name today.

**Comment by tkh44** [comment]
I ended up creating new repo and npm module so that it would cause minimal breakage.

https://github.com/tkh44/shallow-compare
https://www.npmjs.com/package/shallow-compare

**Comment by ritz078** [comment]
👍

**Comment by ritz078** [comment]
You can add the deprecated text in readme and point them to that repo. So that you don't have to maintain both.

**Comment by tkh44** [comment]
Will do. I deprecated the npm module and pointed that to the new one, but forgot about the readme. Thanks for reminding me.

**Comment by tkh44** [comment]
Readme updated

**Comment by ritz078** [comment]
Thanks for all the effort 👍

**Comment by tkh44** [comment]
No problem at all
